name: deploy-pg-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-pg-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Preparar archivos
        run: |
          echo 'hello world ...'
          ls -la
          touch .env
          echo 'DEV_DATABASE_URL=${{ secrets.PG_CONN }}' >> .env
          cat .env

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/celularesapipostgres:${{ github.sha }} .

      - name: List Docker images
        run: docker images

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/celularesapipostgres:${{ github.sha }}
